/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    lateinit private var grid: String

    init {
        grid = "blank_grid"
    }

    val greeting: String
        get() {
            return "Hello World!"
        }
    
    fun printGrid(): String {
        return grid
    }
}

data class Grid(val size: Int) {
    val emptySpace: Char = '⯀'
    lateinit var values: Array<Array<Char>>

    init {
        val row: Array<Char> = Array(size){emptySpace}
        values = Array(size){ row }
    }
}

data class Snake(val coords: Array<Pair<Number,Number>>) {

}

fun main() {
    val testGrid = Grid(25)
    testGrid.values.forEach() {
        println(it.contentToString())
    }
}
