/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    lateinit private var grid: String

    init {
        grid = "blank_grid"
    }

    val greeting: String
        get() {
            return "Hello World!"
        }
    
    fun printGrid(): String {
        return grid
    }
}

fun main() {
    println(App().greeting)
}
